name: CI Pipeline

on: push

jobs:
  build:
    runs-on: [self-hosted, fluidos-cicd-template]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests inside runner system
        run: |
          export PYTHONPATH="$PYTHONPATH:$(pwd)"
          pytest tests/

      - name: Build Docker image
        run: docker build -t fluidos/template-image:latest .

      - name: Run tests inside Docker container
        run: |
          docker run --rm template-image:latest pytest tests/

      - name: Login and Push to Docker Hub Placeholder
        run: echo "Login and push image to Docker Hub"

      # Login to Docker Hub
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fluidos
          password: ${{ secrets.DOCKER_HUB_WRITE_TOKEN }}

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push fluidos/template-image:latest
